### ISSUE TITLE
Visual Studio Setup Project register addin error

### ISSUE THREAD

**Issue by SolidworksDev** [angelsix/solidworks-api#66]
I have ported my Solidworks addin to SolidDna.  I am able to register the addin using the Solidworks Addin Installer from my build area with no problems.  I am using the Nuget package version 1.0.1.8 for my project.  I have created a Visual Studio Setup project to install my addin.  I have written a small console app to register the addin.  The console app has two command line arguments to register and unregister the addin.  It also takes the name of the addin as a second argument.  This all works correctly when I test my console app in my development area.  My problem comes when I run the installer.

When I add my Solidworks addin to to Setup project it adds a number of dependent libraries to the project, which is to be expected.  One of these libraries is System.Runtime.CompilerServices.Unsafe.dll.  When I register the addin with my console app or the Solidworks Addin Installer from the installation location I get the following error in the AngelSix.SolidDna.com-register-log:

[2019-05-20 01:20:03] Registering C:\Program Files (x86)\P&A Addin\PandA SW Addin.dll [AddinIntegration.cs > ComRegister() > Line 334]
[2019-05-20 01:20:03] Configuring plugins... [AddinIntegration.cs > ComRegister() > Line 359]
[2019-05-20 01:20:03] COM Registration error. System.BadImageFormatException: Could not load file or assembly 'file:///C:\Program Files (x86)\P&A Addin\System.Runtime.CompilerServices.Unsafe.dll' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
File name: 'file:///C:\Program Files (x86)\P&A Addin\System.Runtime.CompilerServices.Unsafe.dll' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at AngelSix.SolidDna.PlugInIntegration.GetPlugIns(String pluginFullPath, Action`1 onFound)
   at AngelSix.SolidDna.PlugInIntegration.SolidDnaPlugIns(String addinPath)
   at AngelSix.SolidDna.PlugInIntegration.ConfigurePlugIns(String addinPath)
   at AngelSix.SolidDna.AddInIntegration.ComRegister(Type t)

 [AddinIntegration.cs > ComRegister() > Line 373]

There seems to be a difference between the System.Runtime.CompilerServices.Unsafe.dll in the Nuget package and the source for SolidDna. because if I build a project with the my addin source code and use the SolidDna source code instead of the Nuget package I don't see this error.  I can also exclude the System.Runtime.CompilerServices.Unsafe.dll from the list of dependence in my Setup project and I don't see this error.  Not sure if this will cause other errors during execution.

In addition I can copy the version of System.Runtime.CompilerServices.Unsafe.dll from the SolidDna source code area and I don't get the error when registering the addin.  There is also a difference in the size of the two files.  The version that gets installed when using the Nuget package is 22.9 KB and has a creation date of July 19, 2017.  The version from the SolidDna source code is 21.4 KB and has a creation date of April 18, 2019.

I don't know if I have something messed up in my configuration that is causing this.  If I use the smaller System.Runtime.CompilerServices.Unsafe.dll or just excluded it from the install I don't get the registration error.

Do you have any thought as to what I might be doing wrong and is it safe to just leave System.Runtime.CompilerServices.Unsafe.dll out of the installation?  It doesn't seen to be causing a problem with the addin if it is not in the install location.   I would like to be able to deploy my addin to the other engineers in my group using a Setup.msi.  Any help would be greatly appreciated.

**Comment by angelsix** [comment]
Its an issue with 2 different versions of the same dll by the looks. I'd just leave it out of the install as SolidDna already references it so it will come along. If you find issues without adding it, then let me know
